language: php

php:
    - '7.0'
    - '7.1'

sudo: false

addons:
    mariadb: '10.1'

cache:
    directories:
        - node_modules
        - vendor
    yarn: true
    
before_install:
    - composer self-update
    - nvm install node
    - npm update -g npm
    - npm install -g yarn

before_script:
    - phpenv config-rm xdebug.ini
    - mysql -e 'CREATE DATABASE travis_testing'
    - cp .env.travis .env
    - php artisan key:generate
    - php artisan config:clear
    - php artisan migrate --seed

install:
    - composer install --no-interaction
    - yarn

script:
    - npm run prod
    - vendor/bin/phpunit

